Add search option
romanzdk/s3-web-browser pull request #131
Opened 2024-10-10 15:04 UTC by orenc17

2024-10-13 14:01 UTC, romanzdk requested changes

2024-10-13 14:01 UTC, romanzdk commented on app.py
> +            response = s3_client.list_objects_v2(Bucket=bucket_name,
Hi, thanks for the PR! I tried to run your version on my machine but whenever I open any bucket I get "An error occurred
An unknown error occurred: An error occurred (InvalidArgument) when calling the ListObjectsV2 operation: The continuation token provided is incorrect".

2024-10-13 14:01 UTC, romanzdk commented on app.py
> +def search_bucket(bucket_name: str, path: str) -> str:
Unfortunately I was not able to test this out due to the error described below.

2024-10-13 14:27 UTC, orenc17 commented
Hope my fix helps

2024-10-13 14:33 UTC, romanzdk commented
Unfortunately that did not fix the issue. The error happens on line 139 in `view_bucket` function throwing an `botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the ListObjectsV2 operation: The continuation token provided is incorrect` error.

2024-10-13 14:35 UTC, orenc17 commented
can you give me some test credentials? so i could test on my end

2024-10-13 14:44 UTC, orenc17 commented
Can you change the original marker value to None and check?

2024-10-13 14:47 UTC, romanzdk commented
So `marker=None` did not work because a string is expected. I had to (ugly) hack the first request to not use the continuation token at all. Something like 

```python
if not marker:
                response = s3_client.list_objects_v2(Bucket=bucket_name,
                                                 Prefix=path,
                                                 Delimiter="/",
                                                 )
            else:    
                response = s3_client.list_objects_v2(Bucket=bucket_name,
                                                 Prefix=path,
                                                 Delimiter="/",
                                                 ContinuationToken=marker)
```

worked for me. However, when I submit the search I get the same error again. The same issue probably.

2024-10-14 08:44 UTC, romanzdk commented on templates/bucket_contents.html
> +  <input type="submit" value="Submit" />
```suggestion
  <input type="submit" value="Search" />
```

2024-10-14 08:46 UTC, romanzdk commented
Please mention this new feature also in the README

2024-10-14 19:28 UTC, romanzdk commented
Now it fails again on view bucket. The error is on the newly added line that converts list of dicts to set and to list again. Dict is unhashable. Please test the changes before push.

2024-10-14 19:33 UTC, romanzdk commented on templates/bucket_contents.html
> +</form>
```suggestion
<form
  action="{{ url_for('search_bucket', bucket_name=bucket_name, path=path) }}">
  <input class="form-control" name="search" placeholder="{{ search_param }}"
    autocomplete="off" autofocus="autofocus" type="text">
  <button class="btn waves-effect waves-light" type="submit" name="action">
    Search
  </button>
```

2024-10-21 18:41 UTC, romanzdk commented
still an error on view bucket...

```
File "/Users/romanzdk/Repos/s3-browser/app.py", line 163, in view_bucket
    contents = parse_responses(responses, s3_client, bucket_name, search_param)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/romanzdk/Repos/s3-browser/app.py", line 59, in parse_responses
    S3Entry({
TypeError: S3Entry.__init__() missing 1 required positional argument: 'type'
```

2024-10-30 09:21 UTC, merged